name: "Regression Testing with GitHub App token"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  regression-test:
    name: Regression Testing with GitHub App token
    runs-on: ubuntu-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          path: ghas-metrics-report
      
      - name: Test Action
        uses: ./ghas-metrics-report
        env:
          GITHUB_TOKEN: ${{ secrets.SECURITY_TOKEN }}
        with:
          repo: "demo-csharp"
          org: "jcardoso13"
          features: "dependabot, code-scanning, secret-scanning"
          frequency: "daily"
          output-format: "json, pdf, issues"
      - name: report
        run: |
            echo $report-json
            cat $report-json > ./dist/report.json
      - name: upload GHAS metrics report
        uses: actions/upload-artifact@v4
        with:
          name: ghas-metrics-report
          path: ghas-metrics-report/dist/report.json
